services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=ROOTUSER
      - MINIO_ROOT_PASSWORD=CHANGEME123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  viz_ifc-consumer:
    build: 
      context: ./viz_ifc-consumer
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - minio

  viz_lca-consumer:
    build:
      context: ./viz_lca-consumer
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - nosql_db

  viz_cost-consumer:
    build:
      context: ./viz_cost-consumer
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - nosql_db


  nosql_db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - nosql_data:/data/db

volumes:
  minio_data:
  nosql_data:
