services:
  minio:
    image: minio/minio
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-ROOTUSER}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-CHANGEME123}
      MINIO_PORT: ${MINIO_PORT:-9000}
      MINIO_USE_SSL: ${MINIO_USE_SSL:-false}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    container_name: viz-test-kafka-container
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "${KAFKA_IFC_TOPIC:-ifc-files}:1:1, ${KAFKA_LCA_TOPIC:-lca-data}:1:1, ${KAFKA_COST_TOPIC:-cost-data}:1:1"
      KAFKA_BROKER: kafka:9093
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  nhmzh-viz-services_ifc:
    image: yschindel/nhmzh-viz-services_ifc:latest
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-ROOTUSER}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-CHANGEME123}
      MINIO_PORT: ${MINIO_PORT:-9000}
      MINIO_USE_SSL: ${MINIO_USE_SSL:-false}
      MINIO_ENDPOINT: minio
      VIZ_IFC_FRAGMENTS_BUCKET: ${VIZ_IFC_FRAGMENTS_BUCKET:-ifc-fragment-files}
      MINIO_IFC_BUCKET: ${MINIO_IFC_BUCKET:-ifc-files}
      KAFKA_BROKER: kafka:9093
      KAFKA_IFC_TOPIC: ${KAFKA_IFC_TOPIC:-ifc-files}
    depends_on:
      - minio
      - kafka

  nhmzh-viz-services_lca-cost:
    image: yschindel/nhmzh-viz-services_lca-cost:latest
    environment:
      KAFKA_BROKER: kafka:9093
      KAFKA_LCA_TOPIC: lca-data
      KAFKA_COST_TOPIC: cost-data
      VIZ_KAFKA_DATA_GROUP_ID: viz-data
      AZURE_DB_SERVER: ${AZURE_DB_SERVER:-example.database.windows.net}
      AZURE_DB_PORT: ${AZURE_DB_PORT:-1433}
      AZURE_DB_USER: ${AZURE_DB_USER:-userName}
      AZURE_DB_PASSWORD: ${AZURE_DB_PASSWORD:-thisIsNotMyPassword}
      AZURE_DB_DATABASE: ${AZURE_DB_DATABASE:-nhmzh-viz-services-localdev}
    depends_on:
      - minio # This will be replaced with an API endpoint of another service in the future. It will depend on that services instead.
      - kafka

  nhmzh-viz-services_pbi-server:
    image: yschindel/nhmzh-viz-services_pbi-server:latest
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-ROOTUSER}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-CHANGEME123}
      MINIO_PORT: ${MINIO_PORT:-9000}
      MINIO_USE_SSL: ${MINIO_USE_SSL:-false}
      MINIO_ENDPOINT: minio
      VIZ_IFC_FRAGMENTS_BUCKET: ${VIZ_IFC_FRAGMENTS_BUCKET:-ifc-fragment-files}
      MINIO_IFC_BUCKET: ${MINIO_IFC_BUCKET:-ifc-files}
      PBI_SERVER_PORT: ${PBI_SERVER_PORT:-3000}
      PBI_SRV_API_KEY: ${PBI_SRV_API_KEY:-thisIsNotMyApiKey}
    depends_on:
      - minio
    ports:
      - "3000:3000"

volumes:
  minio_data:
