name: VIZ IFC Consumer Tests

on:
  push:
    branches: [main]
    paths:
      - "viz_ifc-consumer/**"
  pull_request:
    branches: [main]
    paths:
      - "viz_ifc-consumer/**"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./viz_ifc-consumer

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
