services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ../.env
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    container_name: viz-test-kafka-container
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "ifc-files:1:1, lca-data:1:1, lca-data:1:1, lca-history:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper


  viz_ifc:
    build: 
      context: ../viz_ifc
      dockerfile: Dockerfile
    env_file:
      - ../.env
    depends_on:
      - minio
      - kafka

  viz_lca-cost:
    build: 
      context: ../viz_lca-cost
      dockerfile: Dockerfile
    env_file:
      - ../.env
    depends_on:
      - kafka
      - minio

  viz_pbi-server:
    build: 
      context: ../viz_pbi-server
      dockerfile: Dockerfile
    env_file:
      - ../.env
    depends_on:
      - minio
    ports:
      - "3000:3000"

volumes:
  minio_data:


